In [1]:
import numpy as np


In [2]:
vowels=np.array(['a','e','i','o','u'])
vowels

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [3]:
ones=np.ones((2,5),dtype=int)
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
myarray1=np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray1

array([[  2.7,  -2. , -19. ],
       [  0. ,   3.4,  99.9],
       [ 10.6,   0. ,  13. ]])

In [6]:
array=np.arange(4,64,4,dtype=float)
myarray2=array.reshape(3,5)
myarray2

array([[ 4.,  8., 12., 16., 20.],
       [24., 28., 32., 36., 40.],
       [44., 48., 52., 56., 60.]])

In [7]:
array1=np.arange(-1,9.50,0.25)
myarray4=array1.reshape(14,3)
myarray4

array([[-1.  , -0.75, -0.5 ],
       [-0.25,  0.  ,  0.25],
       [ 0.5 ,  0.75,  1.  ],
       [ 1.25,  1.5 ,  1.75],
       [ 2.  ,  2.25,  2.5 ],
       [ 2.75,  3.  ,  3.25],
       [ 3.5 ,  3.75,  4.  ],
       [ 4.25,  4.5 ,  4.75],
       [ 5.  ,  5.25,  5.5 ],
       [ 5.75,  6.  ,  6.25],
       [ 6.5 ,  6.75,  7.  ],
       [ 7.25,  7.5 ,  7.75],
       [ 8.  ,  8.25,  8.5 ],
       [ 8.75,  9.  ,  9.25]])

In [8]:
splited=np.array_split(myarray4,3)
splited

[array([[-1.  , -0.75, -0.5 ],
        [-0.25,  0.  ,  0.25],
        [ 0.5 ,  0.75,  1.  ],
        [ 1.25,  1.5 ,  1.75],
        [ 2.  ,  2.25,  2.5 ]]),
 array([[2.75, 3.  , 3.25],
        [3.5 , 3.75, 4.  ],
        [4.25, 4.5 , 4.75],
        [5.  , 5.25, 5.5 ],
        [5.75, 6.  , 6.25]]),
 array([[6.5 , 6.75, 7.  ],
        [7.25, 7.5 , 7.75],
        [8.  , 8.25, 8.5 ],
        [8.75, 9.  , 9.25]])]

In [9]:
myarray4.sum(axis=0)

array([54.25, 57.75, 61.25])

In [10]:
myarray4.max()

9.25

In [11]:
myarray4.min(axis=1)

array([-1.  , -0.25,  0.5 ,  1.25,  2.  ,  2.75,  3.5 ,  4.25,  5.  ,
        5.75,  6.5 ,  7.25,  8.  ,  8.75])

In [12]:
myarray4.mean(axis=1)

array([-0.75,  0.  ,  0.75,  1.5 ,  2.25,  3.  ,  3.75,  4.5 ,  5.25,
        6.  ,  6.75,  7.5 ,  8.25,  9.  ])

In [13]:
myarray4.std(axis=0)

array([3.02334666, 3.02334666, 3.02334666])

In [14]:
ones/3

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [15]:
myarray3=myarray1@myarray2
myarray3

array([[ -873.2,  -946.4, -1019.6, -1092.8, -1166. ],
       [ 4477.2,  4890.4,  5303.6,  5716.8,  6130. ],
       [  614.4,   708.8,   803.2,   897.6,   992. ]])