In [4]:
import numpy as np

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
a.shape

(3,)

In [5]:
a.ndim

1

In [6]:
a.size

3

In [7]:
a.nbytes

24

In [8]:
a.itemsize

8

In [9]:
a.dtype

dtype('int64')

In [10]:
b=np.array([[1,2,3],[4,5.,6]])

In [11]:
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [15]:
a=np.array(["c",1,2])
print(a)

['c' '1' '2']


In [16]:
a.dtype

dtype('<U21')

In [17]:
b.shape

(2, 3)

In [18]:
b.size

6

In [20]:
b.itemsize

8

In [21]:
b.dtype

dtype('float64')

In [22]:
b.ndim

2

In [33]:
c=np.array([[[1,2],[2,3]],[[4,5],[6,7]],[[7,8],[9,10]]], dtype="float")
print(c)

[[[ 1.  2.]
  [ 2.  3.]]

 [[ 4.  5.]
  [ 6.  7.]]

 [[ 7.  8.]
  [ 9. 10.]]]


In [34]:
c.shape

(3, 2, 2)

In [35]:
c.size


12

In [36]:
c.itemsize

8

In [37]:
c.ndim

3

In [38]:
c.dtype

dtype('float64')

## 1D array accesing

In [42]:
a=np.array([1,2,4,'a'])
a

array(['1', '2', '4', 'a'], dtype='<U21')

In [43]:
a[::]

array(['1', '2', '4', 'a'], dtype='<U21')

In [44]:
a[-1::-1]

array(['a', '4', '2', '1'], dtype='<U21')

In [45]:
a[1:2:]

array(['2'], dtype='<U21')

In [47]:
a[::2]

array(['1', '4'], dtype='<U21')

## 2D array accessing

In [48]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [51]:
#accesing specified row
b[1,]

array([4., 5., 6.])

In [56]:
# accesing specified item
b[1,2]

6.0

In [57]:
#acceisng specified column
b[:,2]

array([3., 6.])

In [58]:
b[:,:2]

array([[1., 2.],
       [4., 5.]])

In [59]:
b[:,-1::-1]

array([[3., 2., 1.],
       [6., 5., 4.]])

In [61]:
b[-1::,-1::]

array([[6.]])

## accesing 3D array

In [63]:
c

array([[[ 1.,  2.],
        [ 2.,  3.]],

       [[ 4.,  5.],
        [ 6.,  7.]],

       [[ 7.,  8.],
        [ 9., 10.]]])

In [66]:
c[1,1,1]

7.0

In [68]:
c[2,0,1]

8.0

In [71]:
c[1,::,::]

array([[4., 5.],
       [6., 7.]])

In [72]:
c[1,0,::]

array([4., 5.])

In [73]:
c[::,0,::]

array([[1., 2.],
       [4., 5.],
       [7., 8.]])

In [74]:
c[::,0,1]

array([2., 5., 8.])


# initialize different types of ayyas

## 1.ZEROS

In [81]:
z=np.zeros(5,dtype="int")
z

array([0, 0, 0, 0, 0])

In [83]:
z1=np.zeros((5,2),dtype="int")
z1

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [84]:
z2=np.zeros((5,2,3))
z2

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [86]:
z3=np.zeros((5,2,3,3))
z3

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

## 2.ONES

In [91]:
o=np.ones(5)
o

array([1., 1., 1., 1., 1.])

In [92]:
o1=np.ones((5,3))
o1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [94]:
o2=np.ones((5,3,2),dtype="int")
o2

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

## any other NUmber np.full((shape),value)

In [97]:
n=np.full(5,25)
n

array([25, 25, 25, 25, 25])

In [100]:
n1=np.full((3,2),99,dtype="float")
n1

array([[99., 99.],
       [99., 99.],
       [99., 99.]])

In [102]:
n2=np.full((4,3,2),8.9)
n2

array([[[8.9, 8.9],
        [8.9, 8.9],
        [8.9, 8.9]],

       [[8.9, 8.9],
        [8.9, 8.9],
        [8.9, 8.9]],

       [[8.9, 8.9],
        [8.9, 8.9],
        [8.9, 8.9]],

       [[8.9, 8.9],
        [8.9, 8.9],
        [8.9, 8.9]]])

In [104]:
n3=np.full(b.shape,4)
n3

array([[4, 4, 4],
       [4, 4, 4]])

In [106]:
n4=np.full_like(b,4)
n4

array([[4., 4., 4.],
       [4., 4., 4.]])

In [108]:
n5=np.full_like(o2,5)
n5

array([[[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]]])

## Random

In [110]:
r=np.random.rand(4,2)
r

array([[0.38710325, 0.13425079],
       [0.11860756, 0.99539601],
       [0.09933516, 0.54403024],
       [0.78718425, 0.78057727]])

In [113]:
#np.random.randint(strt,stop-is not included,size=(shape))
r1=np.random.randint(1,7,size=(2,3))
r1

array([[4, 2, 5],
       [1, 1, 3]])

In [119]:
r2=np.random.randint(-4,9,size=(5,3))
r2

array([[ 7,  8,  6],
       [-2,  1,  3],
       [ 4,  7, -1],
       [ 7,  2,  7],
       [ 3, -4,  4]])

## IDENTITY

In [122]:
i=np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [126]:
i1=np.identity(5,dtype="int")
i1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#output
1 1 1 1 1 
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1 
1 1 1 1 1'''

In [131]:
output=np.ones((5,5),dtype="int")
print(output)
inside=np.zeros((3,3),dtype="int")
inside[1,1]=9
print(inside)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [133]:
output[1:4:,1:4:]=inside
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [134]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [135]:
a=np.array([1,2,3])
b=np.copy(a)
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [138]:
a=np.array([[1,2,3],[4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [140]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [143]:
a.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [144]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [151]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [154]:
a=np.arange(0,101,20)
a

array([  0,  20,  40,  60,  80, 100])

# fininding det, inverse, trace, svd,  eigen values,  eigen vectors, matrix Norm etc 

## we use np.linalg.

In [5]:
a=np.array([[1,2,3],[4,5,6],[7,11,9]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 11,  9]])

In [162]:
np.linalg.det(a)

17.999999999999996

In [163]:
np.linalg.inv(a)

array([[-1.16666667,  0.83333333, -0.16666667],
       [ 0.33333333, -0.66666667,  0.33333333],
       [ 0.5       ,  0.16666667, -0.16666667]])

In [167]:
np.linalg.svd(a)

(array([[-0.19458739, -0.60755643, -0.77007203],
        [-0.47295961, -0.62967205,  0.61629726],
        [-0.8593282 ,  0.48413664, -0.16482342]]),
 array([18.41421137,  1.5939703 ,  0.61325226]),
 array([[-0.43997123, -0.66288926, -0.60580784],
        [ 0.16481603,  0.60354321, -0.78010978],
        [ 0.88275761, -0.44307271, -0.15628687]]))

In [171]:
(vales,vectors)=np.linalg.eig(a)

In [173]:
print(vales)
print(vectors)

[17.15914093 -0.73829517 -1.42084576]
[[-0.21734951 -0.90018001 -0.67422093]
 [-0.48850125  0.27104885 -0.23441644]
 [-0.84505959  0.34089362  0.70033925]]


In [175]:
np.linalg.norm(a)

18.49324200890693

In [166]:
np.trace(a)

15

## MATHEMATICS

In [6]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 11,  9]])

In [7]:
a+2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 13, 11]])

In [8]:
a-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  9,  7]])

In [9]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 22, 18]])

In [10]:
a*a

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49, 121,  81]])

In [12]:
b=np.arange(0,9)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
b=b.reshape((3,3))

In [16]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
a+b

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 18, 17]])

In [18]:
a-b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 4, 1]])

In [19]:
a*b

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 77, 72]])

In [21]:
b/a

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.63636364, 0.88888889]])

In [22]:
a**2

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49, 121,  81]])

In [23]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225,  0.0044257 , -0.91113026]])

In [24]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 , -0.99999021,  0.41211849]])

In [25]:
np.log(a)


array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.39789527, 2.19722458]])

In [26]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 5.98741417e+04, 8.10308393e+03]])

In [27]:
a@b

array([[ 24,  30,  36],
       [ 51,  66,  81],
       [ 87, 114, 141]])

In [29]:
a=np.full((3,2),2)
a

array([[2, 2],
       [2, 2],
       [2, 2]])

In [31]:
b=np.full((2,3),3)
b

array([[3, 3, 3],
       [3, 3, 3]])

In [33]:
#a*b        Error 

#ValueError: operands could not be broadcast together with shapes (3,2) (2,3)

In [34]:
a@b

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [35]:
np.matmul(a,b)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

## Statistics

### sum mean max min std median sort 

In [45]:
#sum 
a=np.random.randint(1,10,size=(3,4))
a

array([[8, 2, 5, 7],
       [1, 8, 9, 4],
       [2, 9, 1, 6]])

In [46]:
#sum total array
np.sum(a)

62

In [47]:
#colwise sum
np.sum(a,axis=0)

array([11, 19, 15, 17])

In [48]:
#row wise sum
np.sum(a,axis=1)

array([22, 22, 18])

In [49]:
#min
np.min(a)

1

In [50]:
#col min
np.min(a,axis=0)

array([1, 2, 1, 4])

In [51]:
#row min
np.min(a,axis=1)

array([2, 1, 1])

In [52]:
#max 
np.max(a)

9

In [53]:
#col max
np.max(a,axis=0)

array([8, 9, 9, 7])

In [54]:
#row max
np.max(a,axis=1)

array([8, 9, 9])

In [57]:
#std
np.std(a)

2.9674156357941426

In [58]:
#col std
np.std(a,axis=0)

array([3.09120617, 3.09120617, 3.26598632, 1.24721913])

In [59]:
#row std
np.std(a,axis=1)

array([2.29128785, 3.20156212, 3.20156212])

In [60]:
#mean
np.mean(a)

5.166666666666667

In [62]:
#col mean
np.mean(a,axis=0)

array([3.66666667, 6.33333333, 5.        , 5.66666667])

In [63]:
#row mean
np.mean(a,axis=1)

array([5.5, 5.5, 4.5])

In [64]:
a

array([[8, 2, 5, 7],
       [1, 8, 9, 4],
       [2, 9, 1, 6]])

In [65]:
#sort
np.sort(a)

array([[2, 5, 7, 8],
       [1, 4, 8, 9],
       [1, 2, 6, 9]])

In [66]:
a

array([[8, 2, 5, 7],
       [1, 8, 9, 4],
       [2, 9, 1, 6]])

In [67]:
#col sort
np.sort(a,axis=0)

array([[1, 2, 1, 4],
       [2, 8, 5, 6],
       [8, 9, 9, 7]])

In [68]:
#row sort
np.sort(a,axis=1)

array([[2, 5, 7, 8],
       [1, 4, 8, 9],
       [1, 2, 6, 9]])

In [71]:
#np.mode(a,axis=0) # eroror mode is not there

In [74]:
#median
np.median(a)

5.5

In [75]:
#row meadian
np.median(a,axis=1)

array([6., 6., 4.])

In [77]:
#col median
np.median(a,axis=0)

array([2., 8., 5., 6.])

## stack or joining arrays

In [81]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [83]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [84]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
b=np.array([1,2,3,4,5])

In [87]:
np.vstack(a,b)

TypeError: vstack() takes 1 positional argument but 2 were given

In [89]:
a=np.full((3,2),2)
a

array([[2, 2],
       [2, 2],
       [2, 2]])

In [91]:
b=np.full((3,3),3)
b

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [93]:
np.hstack((a,b))

array([[2, 2, 3, 3, 3],
       [2, 2, 3, 3, 3],
       [2, 2, 3, 3, 3]])

In [95]:
np.vstack((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [97]:
b=np.full((3,2),3)
b

array([[3, 3],
       [3, 3],
       [3, 3]])

In [98]:
np.stack((a,b))

array([[[2, 2],
        [2, 2],
        [2, 2]],

       [[3, 3],
        [3, 3],
        [3, 3]]])

## split arrays
##### np.array_split splits array and adjust if values are less np.split is strict it is used fro equal division

In [99]:
a=np.array([1,2,3,4,5])
print(a)
b=np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5])

In [105]:
# np.split(a,3) error
np.array_split(a,3)

[array([1, 2]), array([3, 4]), array([5])]

In [106]:
np.split(b,3)

[array([[3, 3]]), array([[3, 3]]), array([[3, 3]])]

In [108]:
a=np.random.randint(0,10,size=(2,4))
a

array([[1, 4, 2, 6],
       [9, 6, 2, 3]])

In [109]:
np.array_split(a,2)

[array([[1, 4, 2, 6]]), array([[9, 6, 2, 3]])]

In [111]:
np.array_split(a,2,axis=1)

[array([[1, 4],
        [9, 6]]),
 array([[2, 6],
        [2, 3]])]

In [112]:
np.split(a,2)

[array([[1, 4, 2, 6]]), array([[9, 6, 2, 3]])]

In [113]:
np.hsplit(a,2)

[array([[1, 4],
        [9, 6]]),
 array([[2, 6],
        [2, 3]])]

In [115]:
#np.hsplit(a,3)   ValueError: array split does not result in an equal division

In [117]:
np.vsplit(a,2)

[array([[1, 4, 2, 6]]), array([[9, 6, 2, 3]])]

## load data from text file

In [125]:
filedata=np.genfromtxt("smple.txt",delimiter=",")
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9.,  0.,  1.,  2.],
       [12., 23., 34., 56., 71., 80.]])

In [126]:
filedata=filedata.astype("int")
filedata

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9,  0,  1,  2],
       [12, 23, 34, 56, 71, 80]])

## BOOlean Masking and Advanced indexing

In [128]:
filedata

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9,  0,  1,  2],
       [12, 23, 34, 56, 71, 80]])

In [129]:
filedata>50

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True]])

In [130]:
filedata[filedata>50]

array([56, 71, 80])

In [139]:
filedata[[1,2],:]

array([[ 7,  8,  9,  0,  1,  2],
       [12, 23, 34, 56, 71, 80]])

In [140]:
filedata[:,[0,1]]

array([[ 1,  2],
       [ 7,  8],
       [12, 23]])