In [58]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split

In [59]:
df=pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [60]:
df["experience"]=df["experience"].fillna("Zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       Zero                    8.0                           9      50000
1       Zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [61]:
df.isna().any()

experience                    False
test_score(out of 10)          True
interview_score(out of 10)    False
salary($)                     False
dtype: bool

In [64]:
exp={
    "zero":0,"one":1,"two":2,"three":3,"four":4,"five":5,"six":6,"seven":7,"eight":8,"nine":9,"ten":10,"eleven":11}

In [65]:
def word_to_num(value):
    if pd.isna(value):
        return 0
    value=str(value).lower().strip()
    if value in exp:
        return exp[value]

In [66]:
df["experience"]=df["experience"].apply(word_to_num)

In [67]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [69]:
df["test_score(out of 10)"].fillna(df["test_score(out of 10)"].mean(),inplace=True)

/tmp/ipykernel_63482/1804839115.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["test_score(out of 10)"].fillna(df["test_score(out of 10)"].mean(),inplace=True)


In [70]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0               8.000000                           9      50000
1           0               8.000000                           6      45000
2           5               6.000000                           7      60000
3           2              10.000000                          10      65000
4           7               9.000000                           6      70000
5           3               7.000000                          10      62000
6          10               7.857143                           7      72000
7          11               7.000000                           8      80000

In [71]:
df.isna().any()

experience                    False
test_score(out of 10)         False
interview_score(out of 10)    False
salary($)                     False
dtype: bool

In [74]:
x=df.drop("salary($)",axis="columns")
y=df["salary($)"]

In [75]:
x

experience  test_score(out of 10)  interview_score(out of 10)
0           0               8.000000                           9
1           0               8.000000                           6
2           5               6.000000                           7
3           2              10.000000                          10
4           7               9.000000                           6
5           3               7.000000                          10
6          10               7.857143                           7
7          11               7.000000                           8

In [76]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [77]:
X_train, X_test, y_train, y_test = train_test_split=train_test_split(x,y,test_size=0.2)

In [78]:
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [79]:
lr.score(X_test,y_test)

-8.52939363549822

In [83]:
lasso=Lasso(alpha=1.0)
lasso.fit(X_train,y_train)

Lasso()

In [84]:
lasso.score(X_test,y_test)

-8.519657605592222

In [92]:
ridge=Ridge()
ridge.fit(X_train,y_train)

Ridge()

In [93]:
ridge.score(X_test,y_test)

-8.223445490522943

In [88]:
lr.predict([[2,9,6]])

/home/apiiit123/test/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([48823.28095076])

In [89]:
lr.predict([[12,10,10]])

/home/apiiit123/test/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([84193.41520601])

In [90]:
lasso.predict([[2,9,6]])

/home/apiiit123/test/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(


array([48827.18823102])

In [95]:
lasso.predict([[12,10,10]])

/home/apiiit123/test/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(


array([84197.4553628])

In [96]:
ridge.predict([[12,10,10]])

/home/apiiit123/test/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([83762.69827009])

In [97]:
ridge.predict([[2,9,6]])

/home/apiiit123/test/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([49379.22418485])