In [100]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [101]:
data=pd.read_csv("spam.csv")
data

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [102]:
data.isnull().any()

Category    False
Message     False
dtype: bool

In [103]:
dummy=pd.get_dummies(data.Category)

In [104]:
column=dummy.columns
column

Index(['ham', 'spam'], dtype='object')

In [105]:
data[column]=dummy

In [107]:
data

Category                                            Message    ham   spam
0         ham  Go until jurong point, crazy.. Available only ...   True  False
1         ham                      Ok lar... Joking wif u oni...   True  False
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...  False   True
3         ham  U dun say so early hor... U c already then say...   True  False
4         ham  Nah I don't think he goes to usf, he lives aro...   True  False
...       ...                                                ...    ...    ...
5567     spam  This is the 2nd time we have tried 2 contact u...  False   True
5568      ham               Will ü b going to esplanade fr home?   True  False
5569      ham  Pity, * was in mood for that. So...any other s...   True  False
5570      ham  The guy did some bitching but I acted like i'd...   True  False
5571      ham                         Rofl. Its true to its name   True  False

[5572 rows x 4 columns]

In [108]:
data.drop(["Category","ham"],axis="columns",inplace=True)

In [109]:
data

Message   spam
0     Go until jurong point, crazy.. Available only ...  False
1                         Ok lar... Joking wif u oni...  False
2     Free entry in 2 a wkly comp to win FA Cup fina...   True
3     U dun say so early hor... U c already then say...  False
4     Nah I don't think he goes to usf, he lives aro...  False
...                                                 ...    ...
5567  This is the 2nd time we have tried 2 contact u...   True
5568               Will ü b going to esplanade fr home?  False
5569  Pity, * was in mood for that. So...any other s...  False
5570  The guy did some bitching but I acted like i'd...  False
5571                         Rofl. Its true to its name  False

[5572 rows x 2 columns]

In [110]:
data.isnull().any()

Message    False
spam       False
dtype: bool

# as ml model does not take character we need to transform message also

In [111]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X=v.fit_transform(data["Message"])

In [112]:
X=X.toarray()

In [113]:
y=data["spam"]

In [114]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [115]:
y

0       False
1       False
2        True
3       False
4       False
        ...  
5567     True
5568    False
5569    False
5570    False
5571    False
Name: spam, Length: 5572, dtype: bool

In [116]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [117]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [118]:
X_train.shape

(4457, 8709)

In [119]:
y_train.shape

(4457,)

In [120]:
model=MultinomialNB()

In [121]:
model.fit(X_train,y_train)

MultinomialNB()

In [122]:
model.score(X_test,y_test)

0.979372197309417

In [123]:
emails=[
    "Hey mohan, can we get together to watch football game tomarrow?",
    "Upto 20% discount on parking, exclusive offer just for ypu. Dont miss this reward!"
]

In [124]:
em=v.transform(emails).toarray()
em

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [125]:
model.predict(em)

array([False,  True])

## Using Pipelining

In [127]:
from sklearn.pipeline import Pipeline

In [129]:
clf=Pipeline([
        ("vectorizer",CountVectorizer()),
        ("nb",MultinomialNB())
])

In [131]:
clf.fit(data["Message"],data["spam"])

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [132]:
clf.predict(emails)

array([False,  True])