In [175]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [176]:
df=pd.read_csv("carprices.csv")
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [177]:
x=df.drop(["Sell Price($)"],axis="columns")
x

Car Model  Mileage  Age(yrs)
0                  BMW X5    69000         6
1                  BMW X5    35000         3
2                  BMW X5    57000         5
3                  BMW X5    22500         2
4                  BMW X5    46000         4
5                 Audi A5    59000         5
6                 Audi A5    52000         5
7                 Audi A5    72000         6
8                 Audi A5    91000         8
9   Mercedez Benz C class    67000         6
10  Mercedez Benz C class    83000         7
11  Mercedez Benz C class    79000         7
12  Mercedez Benz C class    59000         5

In [178]:
y=df["Sell Price($)"]
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [179]:
dummy=pd.get_dummies(x)
dummy

Mileage  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5  \
0     69000         6              False              True   
1     35000         3              False              True   
2     57000         5              False              True   
3     22500         2              False              True   
4     46000         4              False              True   
5     59000         5               True             False   
6     52000         5               True             False   
7     72000         6               True             False   
8     91000         8               True             False   
9     67000         6              False             False   
10    83000         7              False             False   
11    79000         7              False             False   
12    59000         5              False             False   

    Car Model_Mercedez Benz C class  
0                             False  
1                             False  
2                             False  
3                             False  
4                             False  
5                             False  
6                             False  
7                             False  
8                             False  
9                              True  
10                             True  
11                             True  
12                             True

In [180]:
d=pd.get_dummies(x["Car Model"])
d

Audi A5  BMW X5  Mercedez Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9     False   False                   True
10    False   False                   True
11    False   False                   True
12    False   False                   True

In [181]:
dummy.columns

Index(['Mileage', 'Age(yrs)', 'Car Model_Audi A5', 'Car Model_BMW X5',
       'Car Model_Mercedez Benz C class'],
      dtype='object')

In [182]:
dummy

Mileage  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5  \
0     69000         6              False              True   
1     35000         3              False              True   
2     57000         5              False              True   
3     22500         2              False              True   
4     46000         4              False              True   
5     59000         5               True             False   
6     52000         5               True             False   
7     72000         6               True             False   
8     91000         8               True             False   
9     67000         6              False             False   
10    83000         7              False             False   
11    79000         7              False             False   
12    59000         5              False             False   

    Car Model_Mercedez Benz C class  
0                             False  
1                             False  
2                             False  
3                             False  
4                             False  
5                             False  
6                             False  
7                             False  
8                             False  
9                              True  
10                             True  
11                             True  
12                             True

In [183]:
dummy.drop("Car Model_Mercedez Benz C class",axis="columns",inplace=True)

In [184]:
dummy

Mileage  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5
0     69000         6              False              True
1     35000         3              False              True
2     57000         5              False              True
3     22500         2              False              True
4     46000         4              False              True
5     59000         5               True             False
6     52000         5               True             False
7     72000         6               True             False
8     91000         8               True             False
9     67000         6              False             False
10    83000         7              False             False
11    79000         7              False             False
12    59000         5              False             False

In [185]:
lr=LinearRegression()
lr.fit(dummy,y)

LinearRegression()

In [186]:
lr.predict([[45000,4,0,0]])

/home/apiiit123/test/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36991.31721061])

In [187]:
lr.predict([[86000,7,0,1]])

/home/apiiit123/test/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11080.74313219])

In [188]:
lr.score(dummy,y)

0.9417050937281082

In [189]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [190]:
dfle = df
dfle["Car Model"]=le.fit_transform(df["Car Model"])

In [191]:
dfle

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [215]:
X= df.drop("Sell Price($)",axis="columns")
X

Car Model  Mileage  Age(yrs)
0           1    69000         6
1           1    35000         3
2           1    57000         5
3           1    22500         2
4           1    46000         4
5           0    59000         5
6           0    52000         5
7           0    72000         6
8           0    91000         8
9           2    67000         6
10          2    83000         7
11          2    79000         7
12          2    59000         5

In [216]:
y=df["Sell Price($)"]
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [217]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

In [218]:
X=X.values
X

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]])

In [219]:
new=ohe.fit_transform(X[:,[0]]).toarray()

In [220]:
new

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [221]:
X

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]])

In [222]:
X=np.delete(X,0,axis=1)
X

array([[69000,     6],
       [35000,     3],
       [57000,     5],
       [22500,     2],
       [46000,     4],
       [59000,     5],
       [52000,     5],
       [72000,     6],
       [91000,     8],
       [67000,     6],
       [83000,     7],
       [79000,     7],
       [59000,     5]])

In [223]:
X=np.concatenate([X,new],axis=1)

In [224]:
X

array([[6.90e+04, 6.00e+00, 0.00e+00, 1.00e+00, 0.00e+00],
       [3.50e+04, 3.00e+00, 0.00e+00, 1.00e+00, 0.00e+00],
       [5.70e+04, 5.00e+00, 0.00e+00, 1.00e+00, 0.00e+00],
       [2.25e+04, 2.00e+00, 0.00e+00, 1.00e+00, 0.00e+00],
       [4.60e+04, 4.00e+00, 0.00e+00, 1.00e+00, 0.00e+00],
       [5.90e+04, 5.00e+00, 1.00e+00, 0.00e+00, 0.00e+00],
       [5.20e+04, 5.00e+00, 1.00e+00, 0.00e+00, 0.00e+00],
       [7.20e+04, 6.00e+00, 1.00e+00, 0.00e+00, 0.00e+00],
       [9.10e+04, 8.00e+00, 1.00e+00, 0.00e+00, 0.00e+00],
       [6.70e+04, 6.00e+00, 0.00e+00, 0.00e+00, 1.00e+00],
       [8.30e+04, 7.00e+00, 0.00e+00, 0.00e+00, 1.00e+00],
       [7.90e+04, 7.00e+00, 0.00e+00, 0.00e+00, 1.00e+00],
       [5.90e+04, 5.00e+00, 0.00e+00, 0.00e+00, 1.00e+00]])

In [226]:
X=np.delete(X,-1,axis=1)

In [227]:
X

array([[6.90e+04, 6.00e+00, 0.00e+00, 1.00e+00],
       [3.50e+04, 3.00e+00, 0.00e+00, 1.00e+00],
       [5.70e+04, 5.00e+00, 0.00e+00, 1.00e+00],
       [2.25e+04, 2.00e+00, 0.00e+00, 1.00e+00],
       [4.60e+04, 4.00e+00, 0.00e+00, 1.00e+00],
       [5.90e+04, 5.00e+00, 1.00e+00, 0.00e+00],
       [5.20e+04, 5.00e+00, 1.00e+00, 0.00e+00],
       [7.20e+04, 6.00e+00, 1.00e+00, 0.00e+00],
       [9.10e+04, 8.00e+00, 1.00e+00, 0.00e+00],
       [6.70e+04, 6.00e+00, 0.00e+00, 0.00e+00],
       [8.30e+04, 7.00e+00, 0.00e+00, 0.00e+00],
       [7.90e+04, 7.00e+00, 0.00e+00, 0.00e+00],
       [5.90e+04, 5.00e+00, 0.00e+00, 0.00e+00]])

In [231]:
model=LinearRegression()
model.fit(X,y)

LinearRegression()

In [234]:
model.predict([[45000,4,0,0]])

array([36991.31721061])

In [233]:
model.predict([[86000,7,0,1]])

array([11080.74313219])

In [235]:
model.score(X,y)

0.9417050937281082