In [1]:
#1D Array called vowels having the elements 'a','e','i','o','u'
import numpy as np
vowel=np.array(['a','e','i','o','u'])
print(vowel)

['a' 'e' 'i' 'o' 'u']


In [6]:
#1D Array to store upto 1st 10 even numbers
even=np.arange(2,21,2)
print(even)

[ 2  4  6  8 10 12 14 16 18 20]


In [7]:
#A 2D Array called ones having 2 rows and 5 columns and all the eleements are set to 1 and dtype int
ones=np.ones((2, 5), dtype=int)
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [80]:
'''Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data:
2.7, -2, -19
0, 3.4, 99.9
10.6, 0, 13'''
myarray1=np.array([[2.7, -2, -19], [0, 3.4, 99.9], [10.6, 0, 13]])
print(myarray1)

[[  2.7  -2.  -19. ]
 [  0.    3.4  99.9]
 [ 10.6   0.   13. ]]


In [83]:
#A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float.
myarray2 = np.arange(4,61,4,dtype=float).reshape(3,5)
print(myarray2)

[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


In [8]:
#Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start=-1,step=0.25 having
#split this array row wise into 3 equal parts and prints the result
myarray4 = np.arange(-1,9.5,0.25).reshape(14,3)
print(myarray4)

[[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]


In [9]:
#Find the sum of all elements columnwise
sum=np.sum(myarray4,axis=0)
print(sum)

[54.25 57.75 61.25]


In [10]:
#Find the max of all elements
max=np.max(myarray4)
print(max)

9.25


In [11]:
#Find the min of all elements in each row
min=np.min(myarray4,axis=1)
print(min)

[-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]


In [12]:
#Find the mean of all elements in each row
mean=np.mean(myarray4,axis=1)
print(mean)

[-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]


In [13]:
#Find the standard deviation colwise
std=np.std(myarray4,axis=0)
print(std)

[3.02334666 3.02334666 3.02334666]


In [14]:
array1=np.arange(1,13).reshape(3,4)
array2=np.arange(13,25).reshape(3,4)
print(array1)
print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [100]:
#Divide the Elements of array ones by 3
new_arr=array1/3
print(new_arr)

[[0.33333333 0.66666667 1.         1.33333333]
 [1.66666667 2.         2.33333333 2.66666667]
 [3.         3.33333333 3.66666667 4.        ]]


In [101]:
#add the arrays array1 and array2
new_mat=array1+array2
print(new_mat)

[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]


In [102]:
#Subtract Array1 from array 2 and store the result in new matrix
new_matr=array2-array1
print(new_matr)

[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]


In [103]:
#multiply array1 and 2 element wise
new_matri=array2*array1
print(new_matri)

[[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]


In [106]:
#Do the Matrix Multiplication of array 1 & 2 and store result in a new array myarray3
myarray3=array1@array2.T
print(myarray3)

[[150 190 230]
 [382 486 590]
 [614 782 950]]
