In [2]:
import pandas as pd
EngAlph=pd.Series(['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'])
EngAlph

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [11]:
Vowels=pd.Series([0,0,0,0,0],['a','e','i','o','u'])
print(Vowels)
Vowels.empty

a    0
e    0
i    0
o    0
u    0
dtype: int64


False

In [23]:
Friends=pd.Series({"Nithin":3,"ABCD":23,"EFGH":22,"IJKL":2,"MNOP":5})
print(Friends)

Nithin     3
ABCD      23
EFGH      22
IJKL       2
MNOP       5
dtype: int64


In [4]:
MTseries=pd.Series()
MTseries

Series([], dtype: object)

In [7]:
if MTseries.empty:
    print("It is Empty")
else:
    print("It is not Empty")

It is Empty


In [19]:
import numpy as nd
m1=nd.array([1,31])
m2=nd.array([1,28])
m3=nd.array([1,31])
m4=nd.array([1,30])
m5=nd.array([1,31])
m6=nd.array([1,30])
m7=nd.array([1,31])
m8=nd.array([1,31])
m9=nd.array([1,30])
m10=nd.array([1,31])
m11=nd.array([1,30])
m12=nd.array([1,31])

In [20]:
MonthDays=pd.Series([m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12],[1,2,3,4,5,6,7,8,9,10,11,12])
MonthDays

1     [1, 31]
2     [1, 28]
3     [1, 31]
4     [1, 30]
5     [1, 31]
6     [1, 30]
7     [1, 31]
8     [1, 31]
9     [1, 30]
10    [1, 31]
11    [1, 30]
12    [1, 31]
dtype: object

In [12]:
Vowels['a':'u']=10
Vowels

a    10
e    10
i    10
o    10
u    10
dtype: int64

In [13]:
Vowels['a':'u']/=2
Vowels

a    5
e    5
i    5
o    5
u    5
dtype: int64

In [60]:
Vowels1=pd.Series([2,5,6,3,8],['a','e','i','o','u'])
Vowels1

a    2
e    5
i    6
o    3
u    8
dtype: int64

In [40]:
Vowels3=Vowels1+Vowels
Vowels3

a     7.0
e    10.0
i    11.0
o     8.0
u    13.0
dtype: float64

In [41]:
Vowels-Vowels1

a    3.0
e    0.0
i   -1.0
o    2.0
u   -3.0
dtype: float64

In [42]:
Vowels*Vowels1

a    10.0
e    25.0
i    30.0
o    15.0
u    40.0
dtype: float64

In [43]:
Vowels/Vowels1

a    2.500000
e    1.000000
i    0.833333
o    1.666667
u    0.625000
dtype: float64

In [65]:
index=['A','E','I','O','U']
Vowels1=pd.Series([2,5,6,3,8],index)
Vowels1

A    2
E    5
I    6
O    3
U    8
dtype: int64

In [66]:
EngAlph.size

26

In [69]:
EngAlph.ndim

1

In [71]:
EngAlph.values

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype=object)

In [14]:
print(Vowels.ndim)
print(Vowels.size)
print(Vowels.values)

1
5
[5 5 5 5 5]


In [15]:
print(Friends.ndim)
print(Friends.size)
print(Friends.values)

1
5
[ 3 23 22  2  5]


In [16]:
print(MTseries.ndim)
print(MTseries.size)
print(MTseries.values)

1
0
[]


In [21]:
print(MonthDays.ndim)
print(MonthDays.size)
print(MonthDays.values)

1
12
[array([ 1, 31]) array([ 1, 28]) array([ 1, 31]) array([ 1, 30])
 array([ 1, 31]) array([ 1, 30]) array([ 1, 31]) array([ 1, 31])
 array([ 1, 30]) array([ 1, 31]) array([ 1, 30]) array([ 1, 31])]


In [38]:
SeriesEmpty=MTseries
SeriesEmpty

Series([], dtype: object)

In [39]:
MonthDays.index.name="monthno"
MonthDays

monthno
1     [1, 31]
2     [1, 28]
3     [1, 31]
4     [1, 30]
5     [1, 31]
6     [1, 30]
7     [1, 31]
8     [1, 31]
9     [1, 30]
10    [1, 31]
11    [1, 30]
12    [1, 31]
dtype: object

In [24]:
Friends[2]

C:\Users\Naga Pavan Bhuma\AppData\Local\Temp\ipykernel_17064\310109665.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Friends[2]


22

In [25]:
Friends[1]

C:\Users\Naga Pavan Bhuma\AppData\Local\Temp\ipykernel_17064\116650755.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Friends[1]


23

In [15]:
EngAlph[4:16]

4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
dtype: object

In [77]:
EngAlph.head(10)

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
dtype: object

In [31]:
EngAlph.tail(10)

16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [26]:
print(MTseries)

Series([], dtype: object)


In [27]:
MonthDays[2:7]

3    [1, 31]
4    [1, 30]
5    [1, 31]
6    [1, 30]
7    [1, 31]
dtype: object

In [43]:
MonthDays.iloc[::-1]

monthno
12    [1, 31]
11    [1, 30]
10    [1, 31]
9     [1, 30]
8     [1, 31]
7     [1, 31]
6     [1, 30]
5     [1, 31]
4     [1, 30]
3     [1, 31]
2     [1, 28]
1     [1, 31]
dtype: object